#!/bin/bash
set -o errexit

cmds="shutdown
reboot
killx"

INPUT=$(echo -e "$cmds" | dmenu $@ -p "Sys:")
test -n "$INPUT"

# aliases
case "$INPUT" in
    shutdown)
        CMD="shutdown -h 0" ;;
    killx)
        CMD="killall Xorg" ;;
    *)
        CMD="$INPUT" ;;
esac

exec $CMD
