#!/bin/bash
set -o errexit

cmds="reboot
shutdown"

INPUT=$(echo -e "$cmds" | dmenu $@ -p "Sys:")
test -n "$INPUT"

# aliases
case "$INPUT" in
    shutdown)
        CMD="shutdown -h 0" ;;
    google)
        CMD="xdg-open http://google.com" ;;
    chromium-work)
        CMD="chromium --user-data-dir=$HOME/.config/chromium_work" ;;
    ranger)
        CMD="urxvtc -e ranger" ;;
    *)
        CMD="$INPUT" ;;
esac

exec $CMD
