#!/bin/bash
set -o errexit

HISTORY="$HOME/.dmenu_history"
test -f "$HISTORY" || touch "$HISTORY"
DATA="$(printf "$(cat "$HISTORY")")\n"
REVERTED_DATA="$(printf "$DATA" | tac | awk '!x[$0]++')"
# INPUT=$(dmenu $@ < "$HISTORY" -p "Recent:")
INPUT=$(printf "$REVERTED_DATA" | dmenu $@ -p "Recent:")

# aliases
case "$INPUT" in
    shutdown)
        CMD="shutdown -h 0" ;;
    *)
        CMD="$INPUT" ;;
esac

isExists=`whereis "$INPUT" | awk '{print $2}'`

if [[ -z "$isExists" ]]; then
    printf "$(cat "$HISTORY" | head -n -1)" > "$HISTORY"

    exit 0;
else
    echo "" >> "$HISTORY"

    exec $CMD
fi

