#!/bin/bash

bash -c "cd dmenu; make"
bash -c "cd dwm; make"
bash -c "cd slock; make"
bash -c "cd statusbar; cargo build --release"
bash -c "cp -rf ./dmenu/{dmenu,dmenu_path,dmenu_run,stest} ./dwm/dwm ./slock/slock ./statusbar/target/release/rust-dwm-status ./bin/"