#!/bin/bash

FILES_DIR="$HOME/.cache/roficlip";
# SEPARATOR="Ћ";

mkdir -p "$FILES_DIR";

umask 000;
exec 9>"$HOME/${0##*/}.lck";
umask 022;
flock -x -n 9 || exit;

while true; do
    PIDS=$(ps axf | grep roficlipd | grep -v grep | awk 'NR>=2 {print $1}' | tr '\n' ' ');
    kill -9 $PIDS &>/dev/null;

    currentValueHash="$(echo "$(xclip -selection c -o)" | sed ':a;N;$!ba;s/\n/\xC2\xA0/g' | sha1sum)";
    currentValueRofi=$(echo "$(xclip -selection c -o)" | sed ':a;N;$!ba;s/\n/\xC2\xA0/g');
    currentValue=$(xclip -selection c -o);
    currentCount="$(ls $FILES_DIR | wc -l)";
    lastValueHash="";
    lastValue="";
    count="1000"; # max entries in clipboard history
    date="$(date +%s%N)";


    # If directory is not empty then take a value from the latest file
    if [ "$(ls -A $FILES_DIR)" ]; then
        lastValue=$(cat "$FILES_DIR/$(ls $FILES_DIR | tail -1)" );
        # filename=$(echo "$content" | sed "s/$SEPARATOR/\n/" | head -1);
        # lastValue=$(echo "$content" | sed "s/$SEPARATOR/\n/" | tail -1);
        lastValueHash="$(echo "$lastValue" | sha1sum)";
    fi

    # echo "$lastValue != $currentValueRofi";

    # If copied value is not equal to the value from latest file
    if [[ "$lastValueHash" != "$currentValueHash" && ! -z "$currentValue" ]]; then
        # Boundary by count files
        if [ "$currentCount" -ge "$count" ]; then
            rm "$FILES_DIR/$(ls $FILES_DIR | sort | head -1)"
        fi

        echo "${currentValue}" | sed ':a;N;$!ba;s/\n/\xC2\xA0/g' > "$FILES_DIR/$date";
        # echo "${currentValue}" | sed ':a;N;$!ba;s/\n/\xC2\xA0/g' > "$FILES_DIR/$date";
        # echo "${date}${SEPARATOR}${currentValue}" | sed ':a;N;$!ba;s/\n/\xC2\xA0/g' > "$FILES_DIR/$date";
    fi

    sleep 0.2;
done
